name: piglowtop
vendor: Kyle Fazzari <kyle@canonical.com>
architecture: [armhf]
version: 0.1.0
icon: icon.svg
summary: "PiGlow Top"
description: "PiGlow Top is a real-time CPU utilization monitor for the Raspberry Pi 2 that displays its output on a PiGlow. Note that this will not work until it is granted access to the i2c hardware available on the device, for example: sudo snappy hw-assign piglowtop.kyrofa /dev/i2c-1"
services:
  - name: piglowtop
    description: "PiGlow Top service"
    start: ./bin/piglowtop
parts:
  piglowtop:
    plugin: go-project
    source: https://github.com/kyrofa/piglowtop
